### ISSUE TITLE
[1.18.1] "NoClassDef Error". Game crashes upon startup.

### ISSUE THREAD

**Issue by aking4125** [TheCosmicNebula/CosmosIndustry#1]
Hello,

This mod seems to crash with a "NoClassDef" Error. Removing this mod fixes the issue. 

cosmoslibrary-1.18.1-5.1.8.10-universal.jar is being used
cosmosindustry-1.18.1-5.0.2.235-beta-universal.ja
[crash-2022-02-11_09.47.10-fml.txt](https://github.com/TheCosmicNebula/CosmosIndustry/files/8049470/crash-2022-02-11_09.47.10-fml.txt)

**Comment by TheCosmicNebula** [comment]
Hi,

That version of CosmosIndustry is not compatible with that specific version of CosmosLibrary. When downloading a file, in the changelog section the relevant version of CosmosLibrary is provided. An updated version will be released shortly that is compatible with the latest version of CosmosLibrary.

[CurseForge](https://www.curseforge.com/minecraft/mc-mods/cosmos-industry/files/3623716#:~:text=CosmosLibrary%3A-,5.1.6.10,-Release%20Type%3A%20Release)

**Comment by TheCosmicNebula** [comment]
@aking4125 A new version has been uploaded to CurseForge, it should be available shortly.
